// <auto-generated />
using System;
using CommunityActivitiesDirectory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityActivitiesDirectory.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122182914_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommunityActivitiesDirectory.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VenueId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A relaxing yoga session suitable for all levels to start the day energized.",
                            EndTime = new DateTime(2026, 3, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "City Park",
                            MaxParticipants = 250,
                            Organizer = "Healthy Living Club",
                            StartTime = new DateTime(2026, 3, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Morning Yoga Session",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An evening event for developers and tech enthusiasts to connect and share ideas.",
                            EndTime = new DateTime(2026, 3, 12, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Innovation Hub",
                            MaxParticipants = 400,
                            Organizer = "Tech Community",
                            StartTime = new DateTime(2026, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tech Networking Evening",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guided photography walk through the historic district with a professional photographer.",
                            EndTime = new DateTime(2026, 3, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Old Town",
                            MaxParticipants = 220,
                            Organizer = "Photo Lovers Group",
                            StartTime = new DateTime(2026, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Photography Walk",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Date = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hands-on workshop focused on building sustainable business strategies.",
                            EndTime = new DateTime(2026, 3, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Conference Room A",
                            MaxParticipants = 300,
                            Organizer = "Business Leaders Network",
                            StartTime = new DateTime(2026, 3, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Business Strategy Workshop",
                            VenueId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn to cook a three-course meal with a professional chef.",
                            EndTime = new DateTime(2026, 3, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Culinary Studio",
                            MaxParticipants = 200,
                            Organizer = "Food & Fun",
                            StartTime = new DateTime(2026, 3, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cooking Masterclass",
                            VenueId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Date = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly discussion of contemporary fiction over coffee.",
                            EndTime = new DateTime(2026, 3, 22, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Community Library",
                            MaxParticipants = 230,
                            Organizer = "Readers Circle",
                            StartTime = new DateTime(2026, 3, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Book Club Meetup",
                            VenueId = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Date = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Group run followed by stretching and refreshments.",
                            EndTime = new DateTime(2026, 3, 23, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Riverside Trail",
                            MaxParticipants = 450,
                            Organizer = "City Runners",
                            StartTime = new DateTime(2026, 3, 23, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Evening Run Club",
                            VenueId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Date = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to digital marketing fundamentals for small businesses.",
                            EndTime = new DateTime(2026, 3, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Training Center",
                            MaxParticipants = 350,
                            Organizer = "Marketing Pros",
                            StartTime = new DateTime(2026, 3, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Marketing Basics Seminar",
                            VenueId = 8
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Date = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guided tour of the latest modern art exhibition.",
                            EndTime = new DateTime(2026, 3, 27, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Art Gallery",
                            MaxParticipants = 280,
                            Organizer = "Arts Association",
                            StartTime = new DateTime(2026, 3, 27, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Art Exhibition Tour",
                            VenueId = 9
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Date = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Local startups pitch ideas to mentors and investors.",
                            EndTime = new DateTime(2026, 3, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Startup Hub",
                            MaxParticipants = 500,
                            Organizer = "Entrepreneurs Network",
                            StartTime = new DateTime(2026, 3, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Startup Pitch Night",
                            VenueId = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Date = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A scenic hiking trip suitable for beginners.",
                            EndTime = new DateTime(2026, 4, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Green Hills",
                            MaxParticipants = 300,
                            Organizer = "Outdoor Adventures",
                            StartTime = new DateTime(2026, 4, 2, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Weekend Hiking Trip",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Date = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Practical workshop on user-centered design principles.",
                            EndTime = new DateTime(2026, 4, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Design Lab",
                            MaxParticipants = 260,
                            Organizer = "Creative Studio",
                            StartTime = new DateTime(2026, 4, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "UI/UX Design Workshop",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Date = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Volunteer event focused on cleaning public spaces.",
                            EndTime = new DateTime(2026, 4, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Downtown Area",
                            MaxParticipants = 500,
                            Organizer = "City Volunteers",
                            StartTime = new DateTime(2026, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Community Cleanup Day",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Date = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore local wines with expert guidance.",
                            EndTime = new DateTime(2026, 4, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Wine Cellar",
                            MaxParticipants = 220,
                            Organizer = "Gourmet Society",
                            StartTime = new DateTime(2026, 4, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wine Tasting Evening",
                            VenueId = 4
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Improve confidence and speaking skills in a supportive environment.",
                            EndTime = new DateTime(2026, 4, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Meeting Room B",
                            MaxParticipants = 240,
                            Organizer = "Toastmasters Group",
                            StartTime = new DateTime(2026, 4, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Public Speaking Practice",
                            VenueId = 5
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Friendly chess competition for intermediate players.",
                            EndTime = new DateTime(2026, 4, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Game Hall",
                            MaxParticipants = 320,
                            Organizer = "Chess Club",
                            StartTime = new DateTime(2026, 4, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chess Tournament",
                            VenueId = 6
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discussion on current trends and future of artificial intelligence.",
                            EndTime = new DateTime(2026, 4, 14, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Auditorium",
                            MaxParticipants = 500,
                            Organizer = "Tech Talks",
                            StartTime = new DateTime(2026, 4, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI Trends Talk",
                            VenueId = 7
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Date = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hands-on introduction to pottery and clay shaping.",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Art Studio",
                            MaxParticipants = 210,
                            Organizer = "Creative Hands",
                            StartTime = new DateTime(2026, 4, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pottery Basics",
                            VenueId = 8
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Date = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn the basics of budgeting, saving, and investing.",
                            EndTime = new DateTime(2026, 4, 18, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Finance Center",
                            MaxParticipants = 380,
                            Organizer = "Finance Advisors",
                            StartTime = new DateTime(2026, 4, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Financial Planning 101",
                            VenueId = 9
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Date = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Outdoor guided meditation session during sunset.",
                            EndTime = new DateTime(2026, 4, 20, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Lakeside Park",
                            MaxParticipants = 270,
                            Organizer = "Mindfulness Group",
                            StartTime = new DateTime(2026, 4, 20, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sunset Meditation",
                            VenueId = 10
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Date = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Practice foreign languages with native speakers.",
                            EndTime = new DateTime(2026, 4, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Cultural Center",
                            MaxParticipants = 420,
                            Organizer = "Global Friends",
                            StartTime = new DateTime(2026, 4, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Language Exchange Night",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Date = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Showcase of student-built robotics projects.",
                            EndTime = new DateTime(2026, 4, 24, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Tech Lab",
                            MaxParticipants = 460,
                            Organizer = "Robotics Club",
                            StartTime = new DateTime(2026, 4, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Robotics Demo Day",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Date = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Improve storytelling skills through guided exercises.",
                            EndTime = new DateTime(2026, 4, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Workshop Room",
                            MaxParticipants = 240,
                            Organizer = "Writers Guild",
                            StartTime = new DateTime(2026, 4, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Creative Writing Workshop",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Date = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn to prepare nutritious meals for the week.",
                            EndTime = new DateTime(2026, 4, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Kitchen Studio",
                            MaxParticipants = 210,
                            Organizer = "Wellness Kitchen",
                            StartTime = new DateTime(2026, 4, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Healthy Meal Prep",
                            VenueId = 4
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Date = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Peer discussion on leadership challenges and solutions.",
                            EndTime = new DateTime(2026, 4, 30, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Executive Lounge",
                            MaxParticipants = 260,
                            Organizer = "Leadership Forum",
                            StartTime = new DateTime(2026, 4, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Leadership Roundtable",
                            VenueId = 5
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Casual city cycling with planned rest stops.",
                            EndTime = new DateTime(2026, 5, 2, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Central Square",
                            MaxParticipants = 340,
                            Organizer = "Urban Cyclists",
                            StartTime = new DateTime(2026, 5, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cycling Meetup",
                            VenueId = 6
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Date = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Group discussion after a classic film screening.",
                            EndTime = new DateTime(2026, 5, 4, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Cinema Hall",
                            MaxParticipants = 390,
                            Organizer = "Film Society",
                            StartTime = new DateTime(2026, 5, 4, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film Discussion Night",
                            VenueId = 7
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Date = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intensive introduction to data analysis tools and methods.",
                            EndTime = new DateTime(2026, 5, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = false,
                            Location = "Training Lab",
                            MaxParticipants = 480,
                            Organizer = "Data Academy",
                            StartTime = new DateTime(2026, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Analytics Bootcamp",
                            VenueId = 8
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Date = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn seasonal garden planning techniques.",
                            EndTime = new DateTime(2026, 5, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Botanical Garden",
                            MaxParticipants = 230,
                            Organizer = "Green Thumb Club",
                            StartTime = new DateTime(2026, 5, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Garden Planning Session",
                            VenueId = 9
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Date = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Orientation session for new volunteers to learn about upcoming community projects.",
                            EndTime = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            Location = "Community Center",
                            MaxParticipants = 300,
                            Organizer = "City Volunteers",
                            StartTime = new DateTime(2026, 5, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Volunteer Orientation",
                            VenueId = 10
                        });
                });

            modelBuilder.Entity("CommunityActivitiesDirectory.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Sports & Fitness"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Arts & Culture"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Business & Education"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Food & Lifestyle"
                        });
                });

            modelBuilder.Entity("CommunityActivitiesDirectory.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "Springfield",
                            Name = "City Park"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Tech Ave",
                            City = "Springfield",
                            Name = "Innovation Hub"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Heritage Rd",
                            City = "Springfield",
                            Name = "Old Town"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Business Blvd",
                            City = "Springfield",
                            Name = "Conference Room A"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Gourmet Ln",
                            City = "Springfield",
                            Name = "Culinary Studio"
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Leisure St",
                            City = "Springfield",
                            Name = "Game Hall"
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 River Rd",
                            City = "Springfield",
                            Name = "Riverside Trail"
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 Skill St",
                            City = "Springfield",
                            Name = "Training Center"
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Culture Ave",
                            City = "Springfield",
                            Name = "Art Gallery"
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Entrepreneur Way",
                            City = "Springfield",
                            Name = "Startup Hub"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CommunityActivitiesDirectory.Models.Activity", b =>
                {
                    b.HasOne("CommunityActivitiesDirectory.Models.Category", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunityActivitiesDirectory.Models.Venue", "Venue")
                        .WithMany("Activities")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityActivitiesDirectory.Models.Category", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("CommunityActivitiesDirectory.Models.Venue", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
